import NavBar from "@/components/NavBar";
import Head from "next/head";
import styles from "@/styles/blog.module.css";

export const getStaticPaths = async () => {
  const response = await fetch(`https://jsonplaceholder.typicode.com/posts`);
  const data = await response.json();
  const paths = data?.map((currentEle) => {
    return {
      params: {
        postId: currentEle?.id.toString(),
      },
    };
  });
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async (context) => {
  const id = context.params.postId;
  const response = await fetch(
    `https://jsonplaceholder.typicode.com/posts/${id}`
  );
  const data = await response.json();
  return {
    props: {
      data,
    },
  };
};

function PostDetails({ data }) {
  return (
    <>
      <Head>
        <title>Blog Details Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <NavBar />
        <h1 className="main_heading">Blog Details</h1>
        <div
          className={`${styles.blog_main_container} ${styles.blog_main_container_inside}`}>
          <h3>{data?.id}</h3>
          <h2>{data?.title}</h2>
          <p>{data?.body}</p>
        </div>
      </div>
    </>
  );
}

export default PostDetails;
